# -*- coding: utf-8 -*-
"""VQA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14S7aWeKF9LChGqXtO5ce5OfsHAUhxhZT

## 下準備
"""

# @title google driveのmount
from google.colab import drive
drive.mount('/content/drive')

# Commented out IPython magic to ensure Python compatibility.
# @title カレントディレクトリを移動
# %cd /content/drive/MyDrive/Colab Notebooks/DLBasics2023_colab/vqa

# @title git cloneを利用してローカル環境にリポジトリをcloneする．
!git clone https://github.com/Tom376/dl_lecture_competition_pub.git

!git config --global init.defualtBranch VQA-competition

# Commented out IPython magic to ensure Python compatibility.
# @title git checkoutを利用して自身が参加するコンペティションのブランチに切り替える．
# %cd dl_lecture_competition_pub
!git checkout VQA-competition

# @title module import

!pip install matplotlib
import matplotlib.pyplot as plt
import re
import random
import time
from statistics import mode
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split

from PIL import Image
import numpy as np
import pandas
import torch
import torch.nn as nn
import torchvision
from torchvision import transforms
from torchvision import models
import os
import shutil
from concurrent.futures import ThreadPoolExecutor
import csv
import torch.nn.functional as F

# @title driveのデータをランタイムにコピー

import time
import os
import csv
from concurrent.futures.thread import ThreadPoolExecutor

# コピーの時間を計る
start = time.time()

# コピー元とコピー先のディレクトリを指定
src_dir = '/content/drive/MyDrive/Colab Notebooks/DLBasics2023_colab/vqa/dl_lecture_competition_pub/data'
dst_dir = '/content/data'

# コピー先ディレクトリを作成
os.makedirs(dst_dir, exist_ok=True)

# コピーするファイルのリストを作成
files_to_copy = []
for root, _, files in os.walk(src_dir):
    for file in files:
      src_file = os.path.join(root, file)
      dst_file = os.path.join(dst_dir, os.path.relpath(src_file, src_dir))
      files_to_copy.append((src_file, dst_file))

# 並列でファイルをコピーする関数
def copy_files(src_dst):
    src_file, dst_file = src_dst
    dst_file_dir = os.path.dirname(dst_file)
    os.makedirs(dst_file_dir, exist_ok=True)
    try:
        shutil.copy2(src_file, dst_file)
    except Exception as e:
        print(f"Failed to copy {src_file} to {dst_file}: {e}")

# ThreadPoolExecutorを使って並列でコピー
with ThreadPoolExecutor(max_workers=24) as executor:
    executor.map(copy_files, files_to_copy)

# ファイルが全てコピーされたかを確認
copied_files = [os.path.join(root, file) for root, _, files in os.walk(dst_dir) for file in files]
missing_files = [src for src, dst in files_to_copy if dst not in copied_files]

if missing_files:
    print(f"Missing files: {missing_files}")
    for file in missing_files:
        print(file)
else:
    print("All files copied successfully.")

print(f"copy time: {time.time() - start:.2f} s")

"""## Base Code"""

# @title Module Import

import re
import random
import time
from statistics import mode

from PIL import Image
import numpy as np
import pandas
import torch
import torch.nn as nn
import torchvision
from torchvision import transforms

# @title Seed Setting


def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

# @title Text Processing

def process_text(text):
    # lowercase
    text = text.lower()

    # 数詞を数字に変換
    num_word_to_digit = {
        'zero': '0', 'one': '1', 'two': '2', 'three': '3', 'four': '4',
        'five': '5', 'six': '6', 'seven': '7', 'eight': '8', 'nine': '9',
        'ten': '10'
    }
    for word, digit in num_word_to_digit.items():
        text = text.replace(word, digit)

    # 小数点のピリオドを削除
    text = re.sub(r'(?<!\d)\.(?!\d)', '', text)

    # 冠詞の削除
    text = re.sub(r'\b(a|an|the)\b', '', text)

    # 短縮形のカンマの追加
    contractions = {
        "dont": "don't", "isnt": "isn't", "arent": "aren't", "wont": "won't",
        "cant": "can't", "wouldnt": "wouldn't", "couldnt": "couldn't"
    }
    for contraction, correct in contractions.items():
        text = text.replace(contraction, correct)

    # 句読点をスペースに変換
    text = re.sub(r"[^\w\s':]", ' ', text)

    # 句読点をスペースに変換
    text = re.sub(r'\s+,', ',', text)

    # 連続するスペースを1つに変換
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# @title データローダーの作成
class VQADataset(torch.utils.data.Dataset):
    def __init__(self, df_path, image_dir, transform=None, answer=True):
        self.transform = transform  # 画像の前処理
        self.image_dir = image_dir  # 画像ファイルのディレクトリ
        self.df = pandas.read_json(df_path)  # 画像ファイルのパス，question, answerを持つDataFrame
        self.answer = answer

        # question / answerの辞書を作成
        self.question2idx = {}
        self.answer2idx = {}
        self.idx2question = {}
        self.idx2answer = {}

        # 質問文に含まれる単語を辞書に追加
        for question in self.df["question"]:
            question = process_text(question)
            words = question.split(" ")
            for word in words:
                if word not in self.question2idx:
                    self.question2idx[word] = len(self.question2idx)
        self.idx2question = {v: k for k, v in self.question2idx.items()}  # 逆変換用の辞書(question)

        if self.answer:
            # 回答に含まれる単語を辞書に追加
            for answers in self.df["answers"]:
                for answer in answers:
                    word = answer["answer"]
                    word = process_text(word)
                    if word not in self.answer2idx:
                        self.answer2idx[word] = len(self.answer2idx)
            self.idx2answer = {v: k for k, v in self.answer2idx.items()}  # 逆変換用の辞書(answer)

    def update_dict(self, dataset):
        """
        検証用データ，テストデータの辞書を訓練データの辞書に更新する．

        Parameters
        ----------
        dataset : Dataset
            訓練データのDataset
        """
        self.question2idx = dataset.question2idx
        self.answer2idx = dataset.answer2idx
        self.idx2question = dataset.idx2question
        self.idx2answer = dataset.idx2answer

    def __getitem__(self, idx):
        """
        対応するidxのデータ（画像，質問，回答）を取得．

        Parameters
        ----------
        idx : int
            取得するデータのインデックス

        Returns
        -------
        image : torch.Tensor  (C, H, W)
            画像データ
        question : torch.Tensor  (vocab_size)
            質問文をone-hot表現に変換したもの
        answers : torch.Tensor  (n_answer)
            10人の回答者の回答のid
        mode_answer_idx : torch.Tensor  (1)
            10人の回答者の回答の中で最頻値の回答のid
        """
        image = Image.open(f"{self.image_dir}/{self.df['image'][idx]}")
        image = self.transform(image)

        # question : 出現した単語のIDにあたるindexだけが1になる配列
        question = np.zeros(len(self.idx2question) + 1)  # 未知語用の要素を追加
        question_words = process_text(self.df["question"][idx]).split(" ") # process_text を追加
        for word in question_words:
            try:
                question[self.question2idx[word]] = 1  # one-hot表現に変換
            except KeyError:
                question[-1] = 1  # 未知語

        if self.answer:
            answers = [self.answer2idx[process_text(answer["answer"])] for answer in self.df["answers"][idx]]
            mode_answer_idx = mode(answers)  # 最頻値を取得（正解ラベル）

            return image, torch.Tensor(question), torch.Tensor(answers), int(mode_answer_idx)

        else:
            return image, torch.Tensor(question)

    def __len__(self):
        return len(self.df)

# @title 評価指標の実装

# 簡単にするならBCEを利用する
def VQA_criterion(batch_pred: torch.Tensor, batch_answers: torch.Tensor):
    total_acc = 0.

    for pred, answers in zip(batch_pred, batch_answers):
        acc = 0.
        for i in range(len(answers)):
            num_match = 0
            for j in range(len(answers)):
                if i == j:
                    continue
                if pred == answers[j]:
                    num_match += 1
            acc += min(num_match / 3, 1)
        total_acc += acc / 10

    return total_acc / len(batch_pred)

# @title モデルの実装

# ResNetを利用できるようにしておく
class BasicBlock(nn.Module):
    expansion = 1

    def __init__(self, in_channels: int, out_channels: int, stride: int = 1):
        super().__init__()

        self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=3, stride=stride, padding=1)
        self.bn1 = nn.BatchNorm2d(out_channels)
        self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3, stride=1, padding=1)
        self.bn2 = nn.BatchNorm2d(out_channels)
        self.relu = nn.ReLU(inplace=True)

        self.shortcut = nn.Sequential()
        if stride != 1 or in_channels != out_channels:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_channels, out_channels, kernel_size=1, stride=stride),
                nn.BatchNorm2d(out_channels)
            )

    def forward(self, x):
        residual = x
        out = self.relu(self.bn1(self.conv1(x)))
        out = self.bn2(self.conv2(out))

        out += self.shortcut(residual)
        out = self.relu(out)

        return out


class BottleneckBlock(nn.Module):
    expansion = 4

    def __init__(self, in_channels: int, out_channels: int, stride: int = 1):
        super().__init__()

        self.conv1 = nn.Conv2d(in_channels, out_channels, kernel_size=1, stride=1)
        self.bn1 = nn.BatchNorm2d(out_channels)
        self.conv2 = nn.Conv2d(out_channels, out_channels, kernel_size=3, stride=stride, padding=1)
        self.bn2 = nn.BatchNorm2d(out_channels)
        self.conv3 = nn.Conv2d(out_channels, out_channels * self.expansion, kernel_size=1, stride=1)
        self.bn3 = nn.BatchNorm2d(out_channels * self.expansion)
        self.relu = nn.ReLU(inplace=True)

        self.shortcut = nn.Sequential()
        if stride != 1 or in_channels != out_channels * self.expansion:
            self.shortcut = nn.Sequential(
                nn.Conv2d(in_channels, out_channels * self.expansion, kernel_size=1, stride=stride),
                nn.BatchNorm2d(out_channels * self.expansion)
            )

    def forward(self, x):
        residual = x
        out = self.relu(self.bn1(self.conv1(x)))
        out = self.relu(self.bn2(self.conv2(out)))
        out = self.bn3(self.conv3(out))

        out += self.shortcut(residual)
        out = self.relu(out)

        return out


class ResNet(nn.Module):
    def __init__(self, block, layers):
        super().__init__()
        self.in_channels = 64

        self.conv1 = nn.Conv2d(3, 64, kernel_size=7, stride=2, padding=3)
        self.bn1 = nn.BatchNorm2d(64)
        self.relu = nn.ReLU(inplace=True)
        self.maxpool = nn.MaxPool2d(kernel_size=3, stride=2, padding=1)

        self.layer1 = self._make_layer(block, layers[0], 64)
        self.layer2 = self._make_layer(block, layers[1], 128, stride=2)
        self.layer3 = self._make_layer(block, layers[2], 256, stride=2)
        self.layer4 = self._make_layer(block, layers[3], 512, stride=2)

        self.avgpool = nn.AdaptiveAvgPool2d((1, 1))
        self.fc = nn.Linear(512 * block.expansion, 512)

    def _make_layer(self, block, blocks, out_channels, stride=1):
        layers = []
        layers.append(block(self.in_channels, out_channels, stride))
        self.in_channels = out_channels * block.expansion
        for _ in range(1, blocks):
            layers.append(block(self.in_channels, out_channels))

        return nn.Sequential(*layers)

    def forward(self, x):
        x = self.relu(self.bn1(self.conv1(x)))
        x = self.maxpool(x)

        x = self.layer1(x)
        x = self.layer2(x)
        x = self.layer3(x)
        x = self.layer4(x)

        x = self.avgpool(x)
        x = x.view(x.size(0), -1)
        x = self.fc(x)

        return x


def ResNet18():
    return ResNet(BasicBlock, [2, 2, 2, 2])


def ResNet50():
    return ResNet(BottleneckBlock, [3, 4, 6, 3])


class VQAModel(nn.Module):
    def __init__(self, vocab_size: int, n_answer: int):
        super().__init__()
        self.resnet = ResNet18()
        self.text_encoder = nn.Linear(vocab_size, 512)

        self.fc = nn.Sequential(
            nn.Linear(1024, 512),
            nn.ReLU(inplace=True),
            nn.Linear(512, n_answer)
        )

    def forward(self, image, question):
        image_feature = self.resnet(image)  # 画像の特徴量
        question_feature = self.text_encoder(question)  # テキストの特徴量

        x = torch.cat([image_feature, question_feature], dim=1)
        x = self.fc(x)

        return x

# @title 学習の実装
def train(model, dataloader, optimizer, criterion, device):
    model.train()

    total_loss = 0
    total_acc = 0
    simple_acc = 0

    start = time.time()
    for image, question, answers, mode_answer in dataloader:
        image, question, answer, mode_answer = \
            image.to(device), question.to(device), answers.to(device), mode_answer.to(device)

        pred = model(image, question)

        loss = criterion(pred, mode_answer.squeeze())

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        total_acc += VQA_criterion(pred.argmax(1), answers)  # VQA accuracy
        simple_acc += (pred.argmax(1) == mode_answer).float().mean().item()  # simple accuracy

    return total_loss / len(dataloader), total_acc / len(dataloader), simple_acc / len(dataloader), time.time() - start


def eval(model, dataloader, optimizer, criterion, device):
    model.eval()

    total_loss = 0
    total_acc = 0
    simple_acc = 0

    start = time.time()
    for image, question, answers, mode_answer in dataloader:
        image, question, answer, mode_answer = \
            image.to(device), question.to(device), answers.to(device), mode_answer.to(device)

        pred = model(image, question)
        loss = criterion(pred, mode_answer.squeeze())

        total_loss += loss.item()
        total_acc += VQA_criterion(pred.argmax(1), answers)  # VQA accuracy
        simple_acc += (pred.argmax(1) == mode_answer).mean().item()  # simple accuracy

    return total_loss / len(dataloader), total_acc / len(dataloader), simple_acc / len(dataloader), time.time() - start

# @title deviceの設定
set_seed(42)
device = "cuda" if torch.cuda.is_available() else "cpu"
print('device:', device)

# @title dataloader / model

transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor()
])
train_dataset = VQADataset(df_path="./data/train.json", image_dir="./data/train", transform=transform)
test_dataset = VQADataset(df_path="./data/valid.json", image_dir="./data/valid", transform=transform, answer=False)
test_dataset.update_dict(train_dataset)

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=128, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=1, shuffle=False)

model = VQAModel(vocab_size=len(train_dataset.question2idx)+1, n_answer=len(train_dataset.answer2idx)).to(device)

# @title 質問，画像，回答の可視化

j = 200
image, question, answers, mode_answer_idx = train_dataset.__getitem__(j)
image = image.permute(1, 2, 0)
question = question.numpy()
answers = answers.numpy()
answers = [train_dataset.idx2answer[id] for id in answers]
mode_answer = train_dataset.idx2answer[mode_answer_idx]

import matplotlib.pyplot as plt
plt.imshow(image)
for i in range(0,len(question)-1):
    if question[i] == 1:
        print(train_dataset.idx2question[i])
print('answers:', answers)
print('mode answer:', mode_answer)

# @title optimizer / criterion

num_epoch = 1
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-5)

# @title train model
for epoch in range(num_epoch):
    train_loss, train_acc, train_simple_acc, train_time = train(model, train_loader, optimizer, criterion, device)
    print(f"【{epoch + 1}/{num_epoch}】\n"
          f"train time: {train_time:.2f} [s]\n"
          f"train loss: {train_loss:.4f}\n"
          f"train acc: {train_acc:.4f}\n"
          f"train simple acc: {train_simple_acc:.4f}")

# @title 提出用ファイルの作成

model.eval()
submission = []
for image, question in test_loader:
    image, question = image.to(device), question.to(device)
    pred = model(image, question)
    pred = pred.argmax(1).cpu().item()
    submission.append(pred)

submission = [train_dataset.idx2answer[id] for id in submission]
#submission = np.array(submission)
#torch.save(model.state_dict(), "model.pth")
#np.save("submission.npy", submission)

print(submission)

"""## Vilt"""

# @title Module Import

import re
import random
import time
from statistics import mode
from PIL import Image
import numpy as np
import pandas
import torch
import torch.nn as nn
import torchvision
from torchvision import transforms
from torch.utils.data import DataLoader
from transformers import ViltProcessor, ViltForQuestionAnswering, ViltConfig
import torch.nn.functional as F

# @title Seed Setting

def set_seed(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    torch.cuda.manual_seed_all(seed)
    torch.backends.cudnn.deterministic = True
    torch.backends.cudnn.benchmark = False

# @title Text Processing

def process_text(text):
    # lowercase
    text = text.lower()

    # 数詞を数字に変換
    num_word_to_digit = {
        'zero': '0', 'one': '1', 'two': '2', 'three': '3', 'four': '4',
        'five': '5', 'six': '6', 'seven': '7', 'eight': '8', 'nine': '9',
        'ten': '10'
    }
    for word, digit in num_word_to_digit.items():
        text = text.replace(word, digit)

    # 小数点のピリオドを削除
    text = re.sub(r'(?<!\d)\.(?!\d)', '', text)

    # 冠詞の削除
    text = re.sub(r'\b(a|an|the)\b', '', text)

    # 短縮形のカンマの追加
    contractions = {
        "dont": "don't", "isnt": "isn't", "arent": "aren't", "wont": "won't",
        "cant": "can't", "wouldnt": "wouldn't", "couldnt": "couldn't"
    }
    for contraction, correct in contractions.items():
        text = text.replace(contraction, correct)

    # 句読点をスペースに変換
    text = re.sub(r"[^\w\s':]", ' ', text)

    # 句読点をスペースに変換
    text = re.sub(r'\s+,', ',', text)

    # 連続するスペースを1つに変換
    text = re.sub(r'\s+', ' ', text).strip()

    return text

# @title データローダの作成

class VQADataset(torch.utils.data.Dataset):
    def __init__(self, df_path, image_dir, transform=None, processor=None, answer=True):
        self.transform = transform  # 画像の前処理
        self.image_dir = image_dir  # 画像ファイルのディレクトリ
        self.df = pandas.read_json(df_path)  # 画像ファイルのパス，question, answerを持つDataFrame
        self.processor = processor
        self.answer = answer

    def __getitem__(self, idx):
        image = Image.open(f"{self.image_dir}/{self.df['image'][idx]}")
        image = self.transform(image)
        question = self.df["question"][idx]
        processed = self.processor(image, question, padding="max_length", truncation=True, return_tensors="pt")

        if self.answer:
            answers = [process_text(answer["answer"]) for answer in self.df["answers"][idx]]
            answers_idx = []
            for word in answers:
                try:
                  id = model.config.label2id[word]
                  answers_idx.append(id)
                except:
                  id = model.config.label2id['unknown']
                  answers_idx.append(id)
            mode_answer_idx = mode(answers_idx)  # 最頻値を取得（正解ラベル）

            return processed, answers_idx, int(mode_answer_idx)
        else:
            return processed

    def __len__(self):
        return len(self.df)

# @title 評価指標の実装

# 簡単にするならBCEを利用する
def VQA_criterion(batch_pred: torch.Tensor, batch_answers: torch.Tensor):
    total_acc = 0.

    for pred, answers in zip(batch_pred, batch_answers):
        acc = 0.
        for i in range(len(answers)):
            num_match = 0
            for j in range(len(answers)):
                if i == j:
                    continue
                if pred == answers[j]:
                    num_match += 1
            acc += min(num_match / 3, 1)
        total_acc += acc / 10

    return total_acc / len(batch_pred)

# @title 学習の実装

def train(processor, model, dataloader, optimizer, criterion, device):
    model.train()

    total_loss = 0
    total_acc = 0
    simple_acc = 0

    start = time.time()

    for processed, answers, mode_answer in dataloader:

        outputs = model(**processed).logits
        outputs = F.log_softmax(outputs, dim=-1) # softmaxで規格化
        outputs.to(device)

        answers_onehot = torch.zeros(3129).to(device)
        for id in answers:
            answers_onehot[id] += 1
        answers_onehot = answers_onehot / len(answers) # 規格化
        answers_onehot = answers_onehot.to(device)

        mode_answer = torch.tensor(mode_answer)
        mode_answer = F.one_hot(mode_answer, num_classes=3129).float().to(device)

        loss = criterion(outputs, mode_answer).to(device)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
        total_acc += VQA_criterion(outputs.argmax(1), answers)  # VQA accuracy
        #mode_answer_idx = mode(answers)  # 最頻値を取得（正解ラベル）

    return total_loss / len(dataloader), total_acc / len(dataloader), 0, time.time() - start

# @title 評価の実装

def eval(model, dataloader, criterion, device):
    model.eval()

    total_loss = 0
    total_acc = 0
    simple_acc = 0

    start = time.time()
    with torch.no_grad():
        for image, question, answers, mode_answer in dataloader:
            outputs = model(image, question).to(device)

            answers_onehot = torch.stack([nn.functional.one_hot(answer, num_classes=n_answer).float() for answer in answers]).mean(dim=0).to(device)

            loss = criterion(outputs, answers_onehot).to(device)

            total_loss += loss.item()
            total_acc += VQA_criterion(outputs.logits.argmax(1), answers)  # VQA accuracy
            #simple_acc += (outputs.logits.argmax(1) == mode_answer).float().mean().item()  # simple accuracy

    return total_loss / len(dataloader), total_acc / len(dataloader), 0, time.time() - start

# @title deviceの設定
set_seed(42)
device = "cuda" if torch.cuda.is_available() else "cpu"
print('device:', device)

# @title collate_fn

from transformers import BatchEncoding
from torch.nn.utils.rnn import pad_sequence

def collate_fn_train(batch):
    images = [item[0]["pixel_values"].squeeze(0).to(device) for item in batch]
    input_ids = [item[0]["input_ids"].squeeze(0).to(device) for item in batch]
    attention_mask = [item[0]["attention_mask"].squeeze(0).to(device) for item in batch]

    # パディング
    input_ids = pad_sequence(input_ids, batch_first=True, padding_value=0)
    attention_mask = pad_sequence(attention_mask, batch_first=True, padding_value=0)
    images = torch.stack(images)

    answers = [item[1] for item in batch]
    mode_answer = [item[2] for item in batch]

    return {
        'pixel_values': images,
        'input_ids': input_ids,
        'attention_mask': attention_mask
    }, answers, mode_answer

def collate_fn_valid(batch):
    images = [item["pixel_values"].squeeze(0).to(device) for item in batch]
    input_ids = [item["input_ids"].squeeze(0).to(device) for item in batch]
    attention_mask = [item["attention_mask"].squeeze(0).to(device) for item in batch]

    # パディング
    input_ids = pad_sequence(input_ids, batch_first=True, padding_value=0)
    attention_mask = pad_sequence(attention_mask, batch_first=True, padding_value=0)
    images = torch.stack(images)

    return {
        'pixel_values': images,
        'input_ids': input_ids,
        'attention_mask': attention_mask
    }

# @title dataloader / model

transform = transforms.Compose([
    transforms.Resize((224, 224))
])

processor = ViltProcessor.from_pretrained("dandelin/vilt-b32-finetuned-vqa")
model = ViltForQuestionAnswering.from_pretrained("dandelin/vilt-b32-finetuned-vqa")
model.to(device)

train_dataset = VQADataset(df_path="./data/train.json", image_dir="./data/train", transform=transform, processor=processor)
test_dataset = VQADataset(df_path="./data/valid.json", image_dir="./data/valid", transform=transform, processor=processor, answer=False)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True, collate_fn=collate_fn_train)
test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False, collate_fn=collate_fn_valid)

# @title optimizer / criterion

num_epoch = 5
criterion = nn.KLDivLoss(reduction='batchmean')
optimizer = torch.optim.AdamW(model.parameters(), lr=5e-5)
#criterion = nn.CrossEntropyLoss()

# @title train model

for epoch in range(num_epoch):
    train_loss, train_acc, train_simple_acc, train_time = train(processor, model, train_loader, optimizer, criterion, device)
    torch.save(model.state_dict(), "model%d.pth" % epoch)

    print(f"【{epoch + 1}/{num_epoch}】\n"
          f"train time: {train_time:.2f} [s]\n"
          f"train loss: {train_loss:.4f}\n"
          f"train acc: {train_acc:.4f}\n"
          f"train simple acc: {train_simple_acc:.4f}")

    model.eval()
    submission = []
    for processed in test_loader:
        outputs = model(**processed).logits
        submission.append(outputs.argmax(-1).item())
    submission = [model.config.id2label[id] for id in submission]
    for i in range(len(submission)):
        if submission[i] == 'unknown':
            submission[i] = 'unanswerable'
    submission = np.array(submission)

    np.save("submission_%d.npy" %epoch, submission)

# @title モデルの保存

torch.save(model.state_dict(), "model.pth")

# @title モデルの読み込み

model.load_state_dict(torch.load('/content/drive/MyDrive/Colab Notebooks/DLBasics2023_colab/vqa/dl_lecture_competition_pub/model1.pth'))

# @title example of question, answer and image

model.eval()

#df_path = "./data/train.json"
df_path = "./data/valid.json"
df = pandas.read_json(df_path)  # 画像ファイルのパス，question, answerを持つDataFrame

id = 2200

# question
questions = df["question"]
question = questions[id]
question = process_text(question)
print("Question:",question)

# answer
#answers = df["answers"]
#answer = answers[id]
#print("Answer:", answer)

# image
#image_dir = "./data/train"  # 画像ファイルのディレクトリ
image_dir = "./data/valid"  # 画像ファイルのディレクトリ
image = Image.open(f"{image_dir}/{df['image'][id]}")

from transformers import ViltProcessor, ViltForQuestionAnswering
import requests
from PIL import Image

print("Predicted answer:", submission[id])

import matplotlib.pyplot as plt
plt.imshow(image)
plt.show()

# @title テストデータに対する推測

model.eval()
submission = []
for processed in test_loader:
    outputs = model(**processed).logits
    pred = outputs.argmax(-1).item()
    submission.append(pred)

submission = [model.config.id2label[id] for id in submission]
for i in range(len(submission)):
    if submission[i] == 'unknown':
        submission[i] = 'unanswerable'
submission = np.array(submission)

# @title 提出用ファイルの作成

np.save("submission.npy", submission)

# @title gpuメモリの解放
!kill -9 $(lsof -t /dev/nvidia*)
